### ISSUE TITLE
Memory leaking issue

### ISSUE THREAD

**Issue by vaygr** [rkosegi/netflow-collector#125]
Hello, recently I realized that `netflow-collector` container has been eating memory uncontrollably.

![shot-2024-10-01_200453](https://github.com/user-attachments/assets/903f241b-07f9-4a70-b6f9-42b35377f8a3)

I'm running the latest 1.0.2 tag with this config:

```yaml
---
netflow_endpoint: 0.0.0.0:2055
telemetry_endpoint: 0.0.0.0:30001
flush_interval: 120
pipeline:
  filter:
    - local-to-local: true
    - match: source_ip
      is: 0.0.0.0
    - match: source_ip
      is: 255.255.255.255
    - match: destination_ip
      is: 0.0.0.0
    - match: destination_ip
      is: 255.255.255.255
  enrich:
    - protocol_name
  metrics:
    prefix: netflow
    items:
      - name: traffic_detail
        description: Traffic detail
        labels:
          - name: sampler
            value: sampler
            converter: ipv4
          - name: source_ip
            value: source_ip
            converter: ipv4
          - name: destination_ip
            value: destination_ip
            converter: ipv4
          - name: protocol
            value: proto_name
            converter: str
```

One thing I noticed this could be due to `flow_traffic_bytes`, `flow_traffic_packets`, `flow_traffic_summary_size_bytes`, `flow_traffic_summary_size_bytes_sum`, `flow_traffic_summary_size_bytes_count` metrics coming from the goflow package that grow for every port, but are practically useless. They result in over 20MB of payload for each scrape. I'm curious if it would be possible to turn them off or what other issue could be. Maximum on the picture above is roughly 2GB of memory.
