### ISSUE TITLE
Panics with specific config

### ISSUE THREAD

**Issue by vaygr** [rkosegi/netflow-collector#7]
Hello, thanks for this collector!

I noticed a few panics with specific configuration.

Adding `bytes` or `packets` as labels like:

```yaml
          - name: bytes
            value: bytes
            converter: uint32
```

results in:

```
panic: interface conversion: interface {} is uint64, not uint32
```

as well as when `converter` is invalid.
